// =============================================================================
// Idempotency / Duplicate Post Prevention
// =============================================================================
//
// Threads API does not provide an idempotency-key mechanism, so we implement
// deduplication at the application layer:
//
//   1. generateDedupeKey() creates a deterministic hash from account + content
//      + optional scheduled time so the same post cannot be submitted twice.
//   2. checkDuplicate() queries the DB to see if a post with the same key
//      already exists in a terminal or active state.
//   3. findExistingAttempt() locates the most recent publish attempt for a post
//      so that a retry can reuse an existing media container instead of creating
//      a new one.
// =============================================================================

import { eq, and, desc, inArray } from "drizzle-orm";
import type { Database } from "@/db";
import { posts, publishAttempts } from "@/db/schema";

// =============================================================================
// Types
// =============================================================================

export interface DuplicateCheckResult {
  isDuplicate: boolean;
  /** The existing post ID if a duplicate was found */
  existingPostId?: string;
  /** The current status of the existing post */
  existingStatus?: string;
}

export interface ExistingAttemptResult {
  /** Whether a usable existing attempt was found */
  found: boolean;
  /** The publish attempt ID */
  attemptId?: string;
  /** A still-valid container ID that can be reused */
  containerId?: string;
  /** The status of the existing attempt */
  attemptStatus?: string;
}

// =============================================================================
// generateDedupeKey
// =============================================================================

/**
 * Creates a deterministic deduplication key from account ID, content, and an
 * optional scheduled time.
 *
 * The key is a hex-encoded SHA-256 hash of the concatenated inputs, ensuring
 * that the same post content for the same account at the same time always
 * produces the same key.
 *
 * @param accountId - The threads account ID
 * @param content - The post text content
 * @param scheduledAt - Optional scheduled publish time (ISO string or Date)
 * @returns A hex string suitable for use as a unique constraint value
 */
export async function generateDedupeKey(
  accountId: string,
  content: string,
  scheduledAt?: string | Date | null,
): Promise<string> {
  // Normalize the scheduled time to minute precision (ignore seconds/ms)
  // so that minor timing differences don't create false negatives
  const timeComponent = scheduledAt
    ? normalizeTimestamp(scheduledAt)
    : "immediate";

  const payload = `${accountId}:${timeComponent}:${content}`;

  // Use Web Crypto API (available in Cloudflare Workers and modern Node)
  const encoder = new TextEncoder();
  const data = encoder.encode(payload);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

// =============================================================================
// checkDuplicate
// =============================================================================

/**
 * Checks whether a post with the given dedupe key already exists in a state
 * that prevents re-creation.
 *
 * A duplicate is detected when an existing post with the same key is in one of
 * these states: published, publishing, scheduled, queued. Posts in draft or
 * failed state are NOT considered duplicates (the user may intentionally retry).
 *
 * @param db - Drizzle database instance
 * @param dedupeKey - The key generated by generateDedupeKey()
 * @returns DuplicateCheckResult indicating whether a duplicate was found
 */
export async function checkDuplicate(
  db: Database,
  dedupeKey: string,
): Promise<DuplicateCheckResult> {
  const activeStatuses = ["published", "publishing", "scheduled", "queued"] as const;

  const existing = await db
    .select({
      id: posts.id,
      status: posts.status,
    })
    .from(posts)
    .where(
      and(
        eq(posts.dedupeKey, dedupeKey),
        inArray(posts.status, [...activeStatuses]),
      ),
    )
    .limit(1);

  if (existing.length > 0) {
    const row = existing[0]!;
    return {
      isDuplicate: true,
      existingPostId: row.id,
      existingStatus: row.status,
    };
  }

  return { isDuplicate: false };
}

// =============================================================================
// findExistingAttempt
// =============================================================================

/**
 * Finds the most recent publish attempt for a given post that may contain a
 * reusable media container ID.
 *
 * When a publish flow fails midway (e.g., container was created but publish
 * call failed), this function locates the attempt so the retry logic can:
 *   - Reuse the container if it is still in a usable state (creating, processing, polling)
 *   - Skip container creation if the container has already been published
 *   - Create a new container if the previous one expired or errored
 *
 * @param db - Drizzle database instance
 * @param postId - The post ID to look up attempts for
 * @returns ExistingAttemptResult with container info if available
 */
export async function findExistingAttempt(
  db: Database,
  postId: string,
): Promise<ExistingAttemptResult> {
  const reusableStatuses = [
    "creating",
    "processing",
    "polling",
    "publishing",
  ] as const;

  const latestAttempt = await db
    .select({
      id: publishAttempts.id,
      containerId: publishAttempts.containerId,
      status: publishAttempts.status,
    })
    .from(publishAttempts)
    .where(eq(publishAttempts.postId, postId))
    .orderBy(desc(publishAttempts.createdAt))
    .limit(1);

  if (latestAttempt.length === 0) {
    return { found: false };
  }

  const attempt = latestAttempt[0]!;

  // If the attempt already published, the post should not be retried
  if (attempt.status === "published") {
    return {
      found: true,
      attemptId: attempt.id,
      containerId: attempt.containerId ?? undefined,
      attemptStatus: "published",
    };
  }

  // If the container is in a reusable state, return it for resume
  if (
    attempt.containerId &&
    (reusableStatuses as readonly string[]).includes(attempt.status)
  ) {
    return {
      found: true,
      attemptId: attempt.id,
      containerId: attempt.containerId,
      attemptStatus: attempt.status,
    };
  }

  // Container is expired, failed, or missing; caller should create a new one
  return {
    found: true,
    attemptId: attempt.id,
    attemptStatus: attempt.status,
  };
}

// =============================================================================
// Private helpers
// =============================================================================

/**
 * Normalizes a timestamp to minute precision for consistent hashing.
 * Two scheduled times that differ only in seconds will produce the same key.
 */
function normalizeTimestamp(input: string | Date): string {
  const date = typeof input === "string" ? new Date(input) : input;
  // Floor to the nearest minute
  date.setSeconds(0, 0);
  return date.toISOString();
}
