import { migrate } from "drizzle-orm/d1/migrator";
import { createDb } from "./index";

/**
 * Run database migrations against a D1 instance.
 *
 * In production this is typically called during application startup
 * or from a dedicated migration script. The migrations folder is
 * generated by `drizzle-kit generate`.
 *
 * Usage:
 *   await runMigrations(env.DB);
 */
export async function runMigrations(d1: D1Database) {
  const db = createDb(d1);
  await migrate(db, { migrationsFolder: "./drizzle/migrations" });
}
